use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let stdlib_dir = Path::new("src/wasm/stdlib");

    println!("cargo:rerun-if-changed={}", stdlib_dir.display());

    let mut packages: Vec<(String, Vec<String>)> = Vec::new();

    if let Ok(entries) = fs::read_dir(stdlib_dir) {
        let mut dirs: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
            .collect();
        dirs.sort_by_key(|e| e.file_name());

        for dir_entry in dirs {
            let pkg_name = dir_entry.file_name().to_string_lossy().to_string();
            let pkg_path = dir_entry.path();

            println!("cargo:rerun-if-changed={}", pkg_path.display());

            let mut go_files: Vec<String> = Vec::new();
            if let Ok(files) = fs::read_dir(&pkg_path) {
                let mut file_entries: Vec<_> = files
                    .filter_map(|e| e.ok())
                    .filter(|e| {
                        e.path()
                            .extension()
                            .map(|ext| ext == "go")
                            .unwrap_or(false)
                    })
                    .collect();
                file_entries.sort_by_key(|e| e.file_name());

                for file_entry in file_entries {
                    let rel_path = format!(
                        "{}/{}",
                        pkg_name,
                        file_entry.file_name().to_string_lossy()
                    );
                    go_files.push(rel_path);
                    println!("cargo:rerun-if-changed={}", file_entry.path().display());
                }
            }

            if !go_files.is_empty() {
                packages.push((pkg_name, go_files));
            }
        }
    }

    let out_path = stdlib_dir.join("stdlib_generated.rs");
    let mut out = fs::File::create(&out_path).expect("failed to create stdlib_generated.rs");

    writeln!(out, "// Auto-generated by build.rs -- do not edit").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "pub fn get_stdlib_sources(pkg: &str) -> Option<&'static [&'static str]> {{"
    )
    .unwrap();
    writeln!(out, "    match pkg {{").unwrap();

    for (pkg_name, files) in &packages {
        writeln!(out, "        \"{}\" => Some(&[", pkg_name).unwrap();
        for file in files {
            writeln!(out, "            include_str!(\"{}\"),", file).unwrap();
        }
        writeln!(out, "        ]),").unwrap();
    }

    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}
