[package]
name = "gno-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = {version = "0.24.1", features = ["derive"]}
unic-ucd-category = {version = "0.9.0"}
ahash = "0.8.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "fibonacci"
harness = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = true

[profile.bench]
debug = true