[package]
name = "gno-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "parser",
    "vm"
]

[dependencies]
vm = { path = "./vm" }
parser = { path = "./parser" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "fibonacci"
harness = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = true
